"use strict";
const $=id=>document.getElementById(id); let exposures=[],lineRows=[];
const val=id=>{const x=$(id).value.trim();if(x==="")return null;const n=Number(x);return Number.isFinite(n)?n:null};
const pct=(n,d)=>n!==null&&d!==null&&d>0?n/d:null, fp=x=>x===null?"—":(100*x).toFixed(1)+"%";
const dateObj=s=>s?new Date(s+"T00:00:00"):null, iso=d=>d&&Number.isFinite(d.getTime())?d.toISOString().slice(0,10):"—";
function addDays(s,n){const d=dateObj(s);if(!d)return null;d.setDate(d.getDate()+n);return d}
function diffDays(a,b){const A=dateObj(a),B=dateObj(b);return A&&B?Math.floor((B-A)/86400000):null}
function erf(x){const s=x<0?-1:1;x=Math.abs(x);const a1=.254829592,a2=-.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429,p=.3275911,t=1/(1+p*x);return s*(1-(((((a5*t+a4)*t+a3)*t+a2)*t+a1)*t*Math.exp(-x*x)))}
const cdf=z=>.5*(1+erf(z/Math.sqrt(2)));
function rrStats(a,b,c,d){if([a,b,c,d].some(x=>x===null)||a+b<=0||c+d<=0)return null;let A=a,B=b,C=c,D=d;if([A,B,C,D].some(x=>x===0)){A+=.5;B+=.5;C+=.5;D+=.5}const re=A/(A+B),ru=C/(C+D),rr=re/ru,se=Math.sqrt(1/A-1/(A+B)+1/C-1/(C+D)),lo=Math.exp(Math.log(rr)-1.96*se),hi=Math.exp(Math.log(rr)+1.96*se),n=A+B+C+D,r1=A+B,r2=C+D,c1=A+C,c2=B+D,chi=n*Math.pow(A*D-B*C,2)/(r1*r2*c1*c2),p=Math.max(0,Math.min(1,2*(1-cdf(Math.sqrt(chi)))));return{rr,lo,hi,p,re:a/(a+b),ru:c/(c+d)}}
const ptxt=p=>p<.001?"<0.001":p.toFixed(3), escapeHTML=s=>s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function overview(){const pop=val("population"),cases=val("cases"),deaths=val("deaths"),h=val("hospitalised"),contacts=val("contacts"),secondary=val("secondary");$("kCases").textContent=cases??"—";$("kAR").textContent=fp(pct(cases,pop));$("kCFR").textContent=fp(pct(deaths,cases));$("kSAR").textContent=fp(pct(secondary,contacts));$("kHosp").textContent=fp(pct(h,cases));const w=[];if(pop!==null&&cases!==null&&cases>pop)w.push("Total cases exceed the population at risk.");if(cases!==null&&deaths!==null&&deaths>cases)w.push("Deaths exceed total cases.");if(cases!==null&&h!==null&&h>cases)w.push("Hospitalised cases exceed total cases.");if(contacts!==null&&secondary!==null&&secondary>contacts)w.push("Secondary cases exceed susceptible contacts.");$("qc").innerHTML=w.length?w.map(x=>`<div class="warn">⚠ ${x}</div>`).join(""):`<div class="ok">✓ No basic denominator inconsistencies detected.</div>`;drawCurve()}
function parseDates(){return $("dates").value.split(/\n|,/).map(x=>x.trim()).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)&&!isNaN(dateObj(x)))}
function syncCaseDates(){const ds=parseDates().sort();if(ds.length){if(!$("indexOnset").dataset.manual)$("indexOnset").value=ds[0];if(!$("lastOnset").dataset.manual)$("lastOnset").value=ds[ds.length-1]}}
function closureDays(){const mode=$("closureMultiplier").value;if(mode==="custom")return val("customDays");const inc=val("maxIncubation");return inc?inc*Number(mode):null}
function updateClosure(redraw=true){syncCaseDates();const index=$("indexOnset").value,last=$("lastOnset").value,review=$("reviewDate").value,days=closureDays();$("cIndex").textContent=index||"—";$("cLast").textContent=last||"—";$("cWindow").textContent=days?days+" days":"—";const projected=last&&days?addDays(last,days):null;$("cProjected").textContent=projected?iso(projected):"—";const since=last&&review?diffDays(last,review):null;$("cSince").textContent=since===null?"—":since+" days";const box=$("closureStatus");if(!last||!days||!review){box.className="closure-status neutral";box.innerHTML="<b>Closure status unavailable.</b><span>Enter last-case onset, observation rule and review date.</span>"}else if(since>=days){box.className="closure-status eligible";box.innerHTML=`<b>Eligible for closure review</b><span>${since} case-free days observed; ${days} required by the selected rule.</span>`}else{box.className="closure-status monitoring";box.innerHTML=`<b>Continue outbreak monitoring</b><span>${since} case-free days observed; ${days-since} more day(s) to the projected review date if no new case occurs.</span>`}if(redraw)drawCurve(false)}
function drawCurve(doClosure=true){const dates=parseDates(),counts={};dates.forEach(x=>counts[x]=(counts[x]||0)+1);const data=Object.entries(counts).sort();syncCaseDates();const svg=$("epi");svg.innerHTML="";const NS="http://www.w3.org/2000/svg",add=(t,a={},txt="")=>{const e=document.createElementNS(NS,t);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));e.textContent=txt;svg.appendChild(e);return e};const W=1000,H=430,L=65,R=30,T=60,B=85;add("line",{x1:L,y1:H-B,x2:W-R,y2:H-B,stroke:"#8aa0ad","stroke-width":1.5});add("line",{x1:L,y1:T,x2:L,y2:H-B,stroke:"#8aa0ad","stroke-width":1.5});if(!data.length){add("text",{x:L+20,y:T+35,fill:"#7c8b95","font-size":14},"No onset dates available.");$("curveMeta").textContent="No onset data";return}
const max=Math.max(...data.map(x=>x[1])),first=dateObj(data[0][0]),lastData=dateObj(data[data.length-1][0]);let end=new Date(lastData);const proj=$("lastOnset").value&&closureDays()?addDays($("lastOnset").value,closureDays()):null,review=dateObj($("reviewDate").value);[proj,review].filter(Boolean).forEach(d=>{if(d>end)end=new Date(d)});const totalDays=Math.max(1,Math.round((end-first)/86400000)+1),plotW=W-L-R,ph=H-T-B,xFor=s=>L+(diffDays(data[0][0],s)/Math.max(1,totalDays-1))*plotW;
for(let i=0;i<=5;i++){const y=H-B-(i/5)*ph,v=Math.round(max*i/5);add("line",{x1:L,y1:y,x2:W-R,y2:y,stroke:"#e4ebef"});add("text",{x:L-10,y:y+4,"text-anchor":"end",fill:"#71818c","font-size":10},v)}
data.forEach(([date,n])=>{const x=xFor(date),bw=Math.max(9,Math.min(42,plotW/totalDays*.75)),h=n/max*ph,y=H-B-h;add("rect",{x:x-bw/2,y,width:bw,height:h,rx:3,fill:"#159a9c"});add("text",{x,y:y-6,"text-anchor":"middle","font-size":10,fill:"#43545f"},n)});
const marker=(s,label,color,dash="")=>{if(!s)return;const d=dateObj(s);if(!d||d<first||d>end)return;const x=xFor(s);add("line",{x1:x,y1:T-20,x2:x,y2:H-B+5,stroke:color,"stroke-width":2,"stroke-dasharray":dash});add("text",{x:x+4,y:T-30,fill:color,"font-size":10,"font-weight":700},label)};
marker($("indexOnset").value,"INDEX CASE","#315b7d","5 4");marker($("lastOnset").value,"LAST CASE","#c84b4b","5 4");if(proj)marker(iso(proj),"PROJECTED CLOSURE REVIEW","#d99118","6 4");if(review)marker($("reviewDate").value,"REVIEW DATE","#635b9b","3 3");
for(let i=0;i<totalDays;i++){if(totalDays>18&&i%Math.ceil(totalDays/14)!==0)continue;const d=new Date(first);d.setDate(d.getDate()+i);const s=iso(d),x=xFor(s),ty=H-B+20;add("text",{x,y:ty,transform:`rotate(-42 ${x} ${ty})`,"text-anchor":"end","font-size":9,fill:"#657680"},s.slice(5))}
const peak=data.reduce((a,b)=>b[1]>a[1]?b:a);$("peakDate").textContent=peak[0];$("spanDays").textContent=Math.round((lastData-first)/86400000)+1+" days";$("curveMeta").textContent=`${dates.length} cases · peak ${peak[0]} (${peak[1]})`;if(doClosure)updateClosure(false)}
function renderExposures(){const body=$("expBody");if(!exposures.length){body.innerHTML='<tr><td colspan="7" class="empty">No exposures added.</td></tr>';$("topExposure").textContent="Add one or more candidate exposures to generate an analytical summary.";return}const ranked=[...exposures].sort((x,y)=>y.s.rr-x.s.rr);body.innerHTML=ranked.map((x,i)=>`<tr class="${i===0?"best":""}"><td><b>${escapeHTML(x.name)}</b></td><td>${fp(x.s.re)}</td><td>${fp(x.s.ru)}</td><td><b>${x.s.rr.toFixed(2)}</b></td><td>${x.s.lo.toFixed(2)}–${x.s.hi.toFixed(2)}</td><td>${ptxt(x.s.p)}</td><td><button onclick="removeExposure('${x.id}')">Remove</button></td></tr>`).join("");const x=ranked[0];$("topExposure").innerHTML=`<b>Highest observed risk ratio:</b> ${escapeHTML(x.name)} — RR ${x.s.rr.toFixed(2)} (95% CI ${x.s.lo.toFixed(2)}–${x.s.hi.toFixed(2)}, p ${ptxt(x.s.p)}). This ranking does not by itself establish causality.`}
window.removeExposure=id=>{exposures=exposures.filter(x=>x.id!==id);renderExposures()};
function addExposure(){const name=$("expName").value.trim(),a=val("a"),b=val("b"),c=val("c"),d=val("d");if(!name||[a,b,c,d].some(x=>x===null)){alert("Enter the exposure name and all four 2 × 2 cell counts.");return}const s=rrStats(a,b,c,d);if(!s)return;exposures.push({id:Date.now().toString(),name,s});["expName","a","b","c","d"].forEach(id=>$(id).value="");renderExposures()}
function parseCSV(text){const lines=text.replace(/\r/g,"").split("\n").filter(x=>x.trim());if(!lines.length)return[];const parse=line=>{let out=[],cur="",q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch=='"'){if(q&&line[i+1]=='"'){cur+='"';i++}else q=!q}else if(ch==","&&!q){out.push(cur);cur=""}else cur+=ch}out.push(cur);return out};const h=parse(lines[0]).map(x=>x.trim());return lines.slice(1).map(l=>{const v=parse(l),o={};h.forEach((x,i)=>o[x]=v[i]?.trim()??"");return o})}
const detect=(h,c)=>c.find(x=>h.includes(x))||null;
function analyzeLineList(rows){if(!rows.length)return;const h=Object.keys(rows[0]),age=detect(h,["age","Age","AGE"]),sex=detect(h,["sex","Sex","gender","Gender"]),onset=detect(h,["date_onset","onset_date","dateOfOnset","DateOnset"]),loc=detect(h,["locality","location","Locality","Location"]);let bits=[`<b>${rows.length}</b> records loaded.`];if(age){const a=rows.map(r=>Number(r[age])).filter(Number.isFinite).sort((a,b)=>a-b);if(a.length){const m=a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2;$("medianAge").textContent=m.toFixed(1)+" y";bits.push(`Median age ${m.toFixed(1)} years.`)}}if(sex){const v=rows.map(r=>r[sex].toLowerCase()).filter(Boolean),m=v.filter(x=>["m","male","lelaki"].includes(x)).length;if(v.length){$("malePct").textContent=(100*m/v.length).toFixed(1)+"%";bits.push(`Male ${(100*m/v.length).toFixed(1)}%.`)}}if(onset){const ds=rows.map(r=>r[onset]).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x));if(ds.length){$("dates").value=ds.join("\n");$("indexOnset").dataset.manual="";$("lastOnset").dataset.manual="";drawCurve();bits.push(`${ds.length} valid onset dates detected.`)}}if(loc){const cc={};rows.forEach(r=>{if(r[loc])cc[r[loc]]=(cc[r[loc]]||0)+1});const top=Object.entries(cc).sort((a,b)=>b[1]-a[1])[0];if(top)bits.push(`Most frequent locality: ${escapeHTML(top[0])} (${top[1]} records).`)}$("lineSummary").innerHTML=bits.join(" ")}
function report(){overview();updateClosure();const name=$("outbreakName").value.trim()||"The outbreak",cases=val("cases"),pop=val("population"),deaths=val("deaths"),ar=pct(cases,pop),cfr=pct(deaths,cases),ds=parseDates();let s=`${name} was assessed using the available investigation data. `;if(cases!==null)s+=`${cases} cases were identified`;if(ar!==null)s+=` among a population at risk of ${pop}, giving an attack rate of ${(ar*100).toFixed(1)}%`;s+=". ";if(cfr!==null)s+=`${deaths} death(s) were reported (CFR ${(cfr*100).toFixed(1)}%). `;if(ds.length)s+=`The index/earliest recorded onset was ${$("indexOnset").value}, the peak onset was ${$("peakDate").textContent}, and the latest recorded onset was ${$("lastOnset").value}. `;const days=closureDays(),proj=$("cProjected").textContent;if(days)s+=`Using the selected case-free observation rule of ${days} days, the projected closure-review date is ${proj}, provided no new qualifying case occurs. Current status: ${$("closureStatus").querySelector("b").textContent}. `;if(exposures.length){const x=[...exposures].sort((a,b)=>b.s.rr-a.s.rr)[0];s+=`The highest observed candidate exposure association was ${x.name} (RR ${x.s.rr.toFixed(2)}, 95% CI ${x.s.lo.toFixed(2)}–${x.s.hi.toFixed(2)}, p ${ptxt(x.s.p)}).`} $("reportText").textContent=s}
function demo(){$("outbreakName").value="Acute Gastroenteritis Outbreak";$("disease").value="Acute gastroenteritis";$("location").value="Demo Institution";$("population").value=250;$("cases").value=35;$("hospitalised").value=4;$("deaths").value=1;$("contacts").value=75;$("secondary").value=12;$("maxIncubation").value=3;$("reviewDate").value="2026-09-15";$("dates").value=["2026-09-01","2026-09-01","2026-09-01","2026-09-02","2026-09-02","2026-09-02","2026-09-02","2026-09-03","2026-09-03","2026-09-03","2026-09-03","2026-09-03","2026-09-04","2026-09-04","2026-09-04","2026-09-04","2026-09-04","2026-09-04","2026-09-05","2026-09-05","2026-09-05","2026-09-05","2026-09-05","2026-09-06","2026-09-06","2026-09-06","2026-09-06","2026-09-07","2026-09-07","2026-09-07","2026-09-08","2026-09-08","2026-09-09","2026-09-10","2026-09-11"].join("\n");exposures=[{id:"1",name:"Chicken curry",s:rrStats(20,30,5,45)}];overview();renderExposures();report()}
function reset(){document.querySelectorAll("input:not([type=file]),textarea").forEach(x=>x.value="");exposures=[];lineRows=[];$("closureMultiplier").value="2";$("customWrap").classList.add("hidden");["kCases","kAR","kCFR","kSAR","kHosp","medianAge","malePct","peakDate","spanDays","cIndex","cLast","cWindow","cProjected","cSince"].forEach(id=>$(id).textContent="—");$("qc").innerHTML="";$("lineSummary").textContent="No line list loaded. Manual onset dates can still be entered below.";$("reportText").textContent="Complete the outbreak profile and analyses, then generate the summary.";renderExposures();drawCurve()}
document.addEventListener("DOMContentLoaded",()=>{$("reviewDate").value=new Date().toISOString().slice(0,10);$("calcOverview").onclick=overview;$("drawCurve").onclick=()=>drawCurve();$("updateClosure").onclick=()=>updateClosure();$("addExposure").onclick=addExposure;$("demo").onclick=demo;$("reset").onclick=reset;$("generateReport").onclick=report;$("printReport").onclick=()=>window.print();$("copyReport").onclick=async()=>{await navigator.clipboard.writeText($("reportText").textContent);$("copyReport").textContent="Copied";setTimeout(()=>$("copyReport").textContent="Copy summary",1200)};$("closureMultiplier").onchange=()=>{$("customWrap").classList.toggle("hidden",$("closureMultiplier").value!=="custom");updateClosure()};["indexOnset","lastOnset"].forEach(id=>$(id).addEventListener("change",e=>{e.target.dataset.manual="1";updateClosure()}));["maxIncubation","customDays","reviewDate"].forEach(id=>$(id).addEventListener("change",()=>updateClosure()));$("csvFile").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{lineRows=parseCSV(r.result);analyzeLineList(lineRows)};r.readAsText(f)});drawCurve();renderExposures()});