"use strict";
const $=id=>document.getElementById(id); let exposures=[];
const val=id=>{const e=$(id);if(!e||String(e.value).trim()==="")return null;const n=Number(e.value);return Number.isFinite(n)?n:null};
const pct=(n,d)=>n!==null&&d!==null&&d>0?n/d:null, fp=x=>x===null?"—":(100*x).toFixed(1)+"%";
const dObj=s=>s?new Date(s+"T00:00:00"):null, iso=d=>d&&Number.isFinite(d.getTime())?d.toISOString().slice(0,10):"—";
const addDays=(s,n)=>{const d=dObj(s);if(!d)return null;d.setDate(d.getDate()+n);return d};
const diffDays=(a,b)=>{const A=dObj(a),B=dObj(b);return A&&B?Math.floor((B-A)/86400000):null};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));

const RULES={
 typhoid:{name:"Typhoid / Paratyphoid",mode:"verified",days:42,anchor:"last",basis:"42 days from onset of the last case",detail:"MOH Malaysia 2025: outbreak declared over after no new case for 42 days (2 × average incubation period) from onset of the last case.",source:"https://www.moh.gov.my/images/04-penerbitan/garis-panduan-kkm/2.%20GARIS%20PANDUAN%20PENGURUSAN%20WABAK%20TIFOID%20PARATIFOID%20DI%20MALAYSIA_E%20ISBN.pdf"},
 hepatitis_a:{name:"Hepatitis A",mode:"verified",days:56,anchor:"last",basis:"56 days from onset of the last case",detail:"MOH Malaysia 2025: outbreak declared over after no new case for 56 days, stated as 2 incubation periods using an average incubation period of 28 days, from onset of the last case.",source:"https://www.moh.gov.my/images/04-penerbitan/garis-panduan-kkm/6.%20GARIS%20PANDUAN%20PENGURUSAN%20WABAK%20HEPATITIS%20A%20DI%20MALAYSIA_E%20ISBN.pdf"},
 dysentery:{name:"Dysentery",mode:"manual-ip",anchor:"last",basis:"2 incubation periods of the causative organism from last-case onset",detail:"MOH Malaysia specifies 2 incubation periods of the causative organism. Enter the resulting number of days after the organism is identified.",source:"https://www.moh.gov.my/images/04-penerbitan/garis-panduan-kkm/5.%20GARIS%20PANDUAN%20PENGURUSAN%20WABAK%20DISENTERI%20DI%20MALAYSIA_E%20ISBN.pdf"},
 chikungunya:{name:"Chikungunya",mode:"verified",days:14,anchor:"last",basis:"14 days from onset of the last case",detail:"Official MOH Malaysia chikungunya guidance describes the expected outbreak end date as 14 days after onset of the last case.",source:"https://www.moh.gov.my/moh/images/gallery/Garispanduan/CHIKUNGUNYA.pdf"},
 dengue:{name:"Dengue",mode:"operational",days:14,anchor:"last",basis:"14-day operational outbreak monitoring window",detail:"MOH dengue operational material uses a 14-day outbreak window. V1.2 uses the latest recorded onset as the current monitoring anchor and labels the result as an operational review threshold, not a universal formal closure declaration.",source:"https://infosihat.moh.gov.my/penerbitan-multimedia/garis-panduan.raw?args%5B0%5D=0&element=0dd7fb66-93a8-4ec5-8aad-fe0319bf0722&item_id=1393&method=download&task=callelement"},
 mers:{name:"MERS-CoV",mode:"historical",days:28,anchor:"index",basis:"28-day monitoring period (2 incubation periods)",detail:"MOH Malaysia documented a 28-day outbreak monitoring period in the 2018 Malaysia MERS-CoV event. This is historical operational precedent, not a new universal rule.",source:"https://www.moh.gov.my/images/kenyataan-media/2018/KENYATAAN_AKHBAR_KPK_PENAMATAN_WABAK_MERS-CoV_22_Jan_2018.pdf"},
 measles:{name:"Measles",mode:"manual"},hfmd:{name:"HFMD",mode:"manual"},pertussis:{name:"Pertussis",mode:"manual"},mumps:{name:"Mumps",mode:"manual"},rubella:{name:"Rubella",mode:"manual"},varicella:{name:"Chickenpox / Varicella",mode:"manual"},cholera:{name:"Cholera",mode:"manual"},food_poisoning:{name:"Food Poisoning / AGE",mode:"manual",source:"https://www.moh.gov.my/penerbitan-dan-laporan/dasar-akta-polisi-garis-panduan/garis-panduan-umum-kkm/senarai-garis-panduan-umum-awam/garis-panduan-pengurusan-wabak-keracunan-makanan-di-malaysia"},leptospirosis:{name:"Leptospirosis",mode:"manual"},malaria:{name:"Malaria",mode:"manual"},influenza:{name:"Influenza / ILI",mode:"manual"},covid19:{name:"COVID-19",mode:"manual"},mpox:{name:"Mpox",mode:"manual"},nipah:{name:"Nipah Virus Infection",mode:"manual",source:"https://www.moh.gov.my/penerbitan-dan-laporan/dasar-akta-polisi-garis-panduan/garis-panduan-umum-kkm/senarai-garis-panduan-umum-awam/garis-panduan-pengurusan-jangkitan-virus-nipah-niv-di-malaysia"},other:{name:"Other / Unknown",mode:"manual"}
};
const currentRule=()=>RULES[$("disease").value]||null;
function applyRule(){const r=currentRule(),card=$("diseaseRuleCard"),src=$("ruleSource"),days=$("requiredDays");card.className="disease-rule neutral";src.classList.add("hidden");src.removeAttribute("href");days.readOnly=false;days.value="";if(!r){$("ruleTitle").textContent="Select a disease to load the outbreak-monitoring rule.";$("ruleText").textContent="Only timing criteria verified from official Ministry of Health Malaysia material are auto-calculated.";$("ruleVerification").textContent="Not selected";$("ruleBasis").value="";updateClosure();return}$("ruleTitle").textContent=r.name;$("ruleBasis").value=r.basis||"Current disease-specific guideline required";$("ruleText").textContent=r.detail||"No explicit current MOH Malaysia outbreak-closure timing criterion was verified for V1.2. Manual entry is required.";if(r.source){src.href=r.source;src.classList.remove("hidden")}if(r.mode==="verified"){card.className="disease-rule verified";$("ruleVerification").textContent="✓ MOH timing rule verified";days.value=r.days;days.readOnly=true}else if(r.mode==="operational"||r.mode==="historical"||r.mode==="manual-ip"){card.className="disease-rule operational";$("ruleVerification").textContent=r.mode==="manual-ip"?"◐ MOH rule verified; days are organism-specific":"◐ MOH operational / historical rule";if(r.days){days.value=r.days;days.readOnly=true}}else{card.className="disease-rule manual";$("ruleVerification").textContent="Manual closure verification required"}updateClosure()}
function overview(){const pop=val("population"),c=val("cases"),d=val("deaths"),h=val("hospitalised"),ct=val("contacts"),s=val("secondary");$("kCases").textContent=c??"—";$("kAR").textContent=fp(pct(c,pop));$("kCFR").textContent=fp(pct(d,c));$("kSAR").textContent=fp(pct(s,ct));$("kHosp").textContent=fp(pct(h,c));let w=[];if(pop!==null&&c!==null&&c>pop)w.push("Total cases exceed population at risk.");if(c!==null&&d!==null&&d>c)w.push("Deaths exceed total cases.");$("qc").innerHTML=w.length?w.map(x=>`<div class="warn">⚠ ${x}</div>`).join(""):'<div class="ok">✓ No basic denominator inconsistencies detected.</div>';drawCurve()}
function parseDates(){return $("dates").value.split(/\n|,/).map(x=>x.trim()).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)&&!isNaN(dObj(x)))}
function syncDates(){const ds=parseDates().sort();if(ds.length){if(!$("indexOnset").dataset.manual)$("indexOnset").value=ds[0];if(!$("secondOnset").dataset.manual)$("secondOnset").value=ds[1]||"";if(!$("lastOnset").dataset.manual)$("lastOnset").value=ds[ds.length-1]}}
function anchor(){const r=currentRule();return r&&r.anchor==="index"?$("indexOnset").value:$("lastOnset").value}
function updateClosure(redraw=true){syncDates();const r=currentRule(),a=anchor(),review=$("reviewDate").value,days=val("requiredDays");$("cIndex").textContent=$("indexOnset").value||"—";$("cLast").textContent=$("lastOnset").value||"—";$("cWindow").textContent=days?days+" days":"—";const proj=a&&days?addDays(a,days):null;$("cProjected").textContent=proj?iso(proj):"—";const since=a&&review?diffDays(a,review):null;$("cSince").textContent=since===null?"—":since+" days";const box=$("closureStatus");if(!r){box.className="closure-status neutral";box.innerHTML="<b>Select a disease.</b><span>The rule library will determine whether automatic timing is available.</span>"}else if(!days||!a||!review){box.className="closure-status neutral";box.innerHTML="<b>Timing status unavailable.</b><span>Complete the required fields.</span>"}else if(since<0){box.className="closure-status neutral";box.innerHTML="<b>Check the dates entered.</b><span>Review date precedes the monitoring anchor.</span>"}else if(since>=days){box.className="closure-status eligible";box.innerHTML=`<b>${r.mode==="verified"?"Eligible for closure review":"Timing threshold reached"}</b><span>${since} day(s) observed against ${days} day(s). Confirm all non-timing requirements.</span>`}else{box.className="closure-status monitoring";box.innerHTML=`<b>Continue outbreak monitoring</b><span>${since} day(s) observed; ${days-since} more day(s) if no qualifying case occurs.</span>`}if(redraw)drawCurve(false)}
function drawCurve(doClosure=true){const ds=parseDates(),counts={};ds.forEach(x=>counts[x]=(counts[x]||0)+1);const data=Object.entries(counts).sort();syncDates();const svg=$("epi");svg.innerHTML="";const NS="http://www.w3.org/2000/svg",add=(t,a={},txt="")=>{const e=document.createElementNS(NS,t);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));e.textContent=txt;svg.appendChild(e);return e};const W=1000,H=430,L=65,R=30,T=60,B=85;add("line",{x1:L,y1:H-B,x2:W-R,y2:H-B,stroke:"#8aa0ad"});add("line",{x1:L,y1:T,x2:L,y2:H-B,stroke:"#8aa0ad"});if(!data.length){add("text",{x:L+20,y:T+35,fill:"#7c8b95","font-size":14},"No onset dates available.");$("curveMeta").textContent="No onset data";return}const max=Math.max(...data.map(x=>x[1])),first=dObj(data[0][0]),lastD=dObj(data[data.length-1][0]);let end=new Date(lastD);const days=val("requiredDays"),a=anchor(),proj=a&&days?addDays(a,days):null,review=dObj($("reviewDate").value);[proj,review].filter(Boolean).forEach(d=>{if(d>end)end=new Date(d)});const total=Math.max(1,Math.round((end-first)/86400000)+1),pw=W-L-R,ph=H-T-B,x=s=>L+(diffDays(data[0][0],s)/Math.max(1,total-1))*pw;for(let i=0;i<=5;i++){const y=H-B-(i/5)*ph;add("line",{x1:L,y1:y,x2:W-R,y2:y,stroke:"#e4ebef"});add("text",{x:L-10,y:y+4,"text-anchor":"end","font-size":10,fill:"#71818c"},Math.round(max*i/5))}data.forEach(([date,n])=>{const xx=x(date),bw=Math.max(9,Math.min(42,pw/total*.75)),hh=n/max*ph,y=H-B-hh;add("rect",{x:xx-bw/2,y,width:bw,height:hh,rx:3,fill:"#159a9c"});add("text",{x:xx,y:y-6,"text-anchor":"middle","font-size":10,fill:"#43545f"},n)});const marker=(s,label,color)=>{if(!s)return;const dd=dObj(s);if(!dd||dd<first||dd>end)return;const xx=x(s);add("line",{x1:xx,y1:T-20,x2:xx,y2:H-B+5,stroke:color,"stroke-width":2,"stroke-dasharray":"5 4"});add("text",{x:xx+4,y:T-30,fill:color,"font-size":10,"font-weight":700},label)};marker($("indexOnset").value,"INDEX CASE","#315b7d");marker($("lastOnset").value,"LAST CASE","#c84b4b");if(proj)marker(iso(proj),"PROJECTED REVIEW","#d99118");if(review)marker($("reviewDate").value,"REVIEW DATE","#635b9b");const peak=data.reduce((a,b)=>b[1]>a[1]?b:a);$("peakDate").textContent=peak[0];$("spanDays").textContent=Math.round((lastD-first)/86400000)+1+" days";$("curveMeta").textContent=`${ds.length} cases · peak ${peak[0]} (${peak[1]})`;if(doClosure)updateClosure(false)}
function erf(x){const s=x<0?-1:1;x=Math.abs(x);const a1=.254829592,a2=-.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429,p=.3275911,t=1/(1+p*x);return s*(1-(((((a5*t+a4)*t+a3)*t+a2)*t+a1)*t*Math.exp(-x*x)))}const cdf=z=>.5*(1+erf(z/Math.sqrt(2)));
function rrStats(a,b,c,d){if([a,b,c,d].some(x=>x===null)||a+b<=0||c+d<=0)return null;let A=a,B=b,C=c,D=d;if([A,B,C,D].some(x=>x===0)){A+=.5;B+=.5;C+=.5;D+=.5}const re=A/(A+B),ru=C/(C+D),rr=re/ru,se=Math.sqrt(1/A-1/(A+B)+1/C-1/(C+D)),lo=Math.exp(Math.log(rr)-1.96*se),hi=Math.exp(Math.log(rr)+1.96*se),n=A+B+C+D,r1=A+B,r2=C+D,c1=A+C,c2=B+D,chi=n*Math.pow(A*D-B*C,2)/(r1*r2*c1*c2),p=Math.max(0,Math.min(1,2*(1-cdf(Math.sqrt(chi)))));return{rr,lo,hi,p,re:a/(a+b),ru:c/(c+d)}}
const ptxt=p=>p<.001?"<0.001":p.toFixed(3);
function renderExp(){const body=$("expBody");if(!exposures.length){body.innerHTML='<tr><td colspan="7" class="empty">No exposures added.</td></tr>';$("topExposure").textContent="Add one or more candidate exposures to generate an analytical summary.";return}const r=[...exposures].sort((x,y)=>y.s.rr-x.s.rr);body.innerHTML=r.map((x,i)=>`<tr class="${i===0?'best':''}"><td><b>${esc(x.name)}</b></td><td>${fp(x.s.re)}</td><td>${fp(x.s.ru)}</td><td><b>${x.s.rr.toFixed(2)}</b></td><td>${x.s.lo.toFixed(2)}–${x.s.hi.toFixed(2)}</td><td>${ptxt(x.s.p)}</td><td><button onclick="removeExposure('${x.id}')">Remove</button></td></tr>`).join("");const x=r[0];$("topExposure").innerHTML=`<b>Highest observed RR:</b> ${esc(x.name)} — RR ${x.s.rr.toFixed(2)} (95% CI ${x.s.lo.toFixed(2)}–${x.s.hi.toFixed(2)}, p ${ptxt(x.s.p)}). Ranking does not establish causality.`}
window.removeExposure=id=>{exposures=exposures.filter(x=>x.id!==id);renderExp()};
function addExposure(){const name=$("expName").value.trim(),a=val("a"),b=val("b"),c=val("c"),d=val("d");if(!name||[a,b,c,d].some(x=>x===null)){alert("Enter exposure name and all four 2×2 cells.");return}const s=rrStats(a,b,c,d);if(!s)return;exposures.push({id:Date.now().toString(),name,s});["expName","a","b","c","d"].forEach(id=>$(id).value="");renderExp()}
function parseCSV(text){const lines=text.replace(/\r/g,"").split("\n").filter(x=>x.trim());if(!lines.length)return[];const p=line=>{let o=[],cur="",q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===","&&!q){o.push(cur);cur=""}else cur+=ch}o.push(cur);return o};const h=p(lines[0]).map(x=>x.trim());return lines.slice(1).map(l=>{const v=p(l),o={};h.forEach((x,i)=>o[x]=v[i]?.trim()??"");return o})}
const detect=(h,c)=>c.find(x=>h.includes(x))||null;
function analyze(rows){if(!rows.length)return;const h=Object.keys(rows[0]),age=detect(h,["age","Age","AGE"]),sex=detect(h,["sex","Sex","gender","Gender"]),onset=detect(h,["date_onset","onset_date","DateOnset"]),loc=detect(h,["locality","location","Locality","Location"]);let bits=[`<b>${rows.length}</b> records loaded.`];if(age){const a=rows.map(r=>Number(r[age])).filter(Number.isFinite).sort((a,b)=>a-b);if(a.length){const m=a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2;$("medianAge").textContent=m.toFixed(1)+" y";bits.push(`Median age ${m.toFixed(1)} years.`)}}if(sex){const v=rows.map(r=>r[sex].toLowerCase()).filter(Boolean),m=v.filter(x=>["m","male","lelaki"].includes(x)).length;if(v.length){$("malePct").textContent=(100*m/v.length).toFixed(1)+"%";bits.push(`Male ${(100*m/v.length).toFixed(1)}%.`)}}if(onset){const ds=rows.map(r=>r[onset]).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x));if(ds.length){$("dates").value=ds.join("\n");["indexOnset","secondOnset","lastOnset"].forEach(id=>$(id).dataset.manual="");drawCurve();bits.push(`${ds.length} valid onset dates detected.`)}}if(loc){const cc={};rows.forEach(r=>{if(r[loc])cc[r[loc]]=(cc[r[loc]]||0)+1});const t=Object.entries(cc).sort((a,b)=>b[1]-a[1])[0];if(t)bits.push(`Most frequent locality: ${esc(t[0])} (${t[1]} records).`)}$("lineSummary").innerHTML=bits.join(" ")}
function report(){overview();updateClosure();const name=$("outbreakName").value.trim()||"The outbreak",r=currentRule(),c=val("cases"),pop=val("population"),d=val("deaths"),ar=pct(c,pop),cfr=pct(d,c);let s=`${name} was assessed using the available investigation data. `;if(c!==null)s+=`${c} cases were identified`;if(ar!==null)s+=` among a population at risk of ${pop}, giving an attack rate of ${(ar*100).toFixed(1)}%`;s+=". ";if(cfr!==null)s+=`${d} death(s) were reported (CFR ${(cfr*100).toFixed(1)}%). `;if(parseDates().length)s+=`Earliest recorded onset was ${$("indexOnset").value}, peak onset ${$("peakDate").textContent}, and latest recorded onset ${$("lastOnset").value}. `;if(r)s+=`Disease rule: ${r.name}; ${$("ruleBasis").value}. Projected review date: ${$("cProjected").textContent}. Current status: ${$("closureStatus").querySelector("b").textContent}. `;$("reportText").textContent=s}
function demo(){$("outbreakName").value="Typhoid Outbreak";$("disease").value="typhoid";$("location").value="Demo Institution";$("population").value=250;$("cases").value=35;$("hospitalised").value=4;$("deaths").value=1;$("contacts").value=75;$("secondary").value=12;$("reviewDate").value="2026-10-24";const counts={"2026-09-01":3,"2026-09-02":4,"2026-09-03":5,"2026-09-04":6,"2026-09-05":5,"2026-09-06":4,"2026-09-07":3,"2026-09-08":2,"2026-09-09":1,"2026-09-10":1,"2026-09-11":1};$("dates").value=Object.entries(counts).flatMap(([d,n])=>Array(n).fill(d)).join("\n");applyRule();overview();report()}
function reset(){document.querySelectorAll("input:not([type=file]),textarea").forEach(e=>e.value="");$("disease").value="";exposures=[];["kCases","kAR","kCFR","kSAR","kHosp","medianAge","malePct","peakDate","spanDays","cIndex","cLast","cWindow","cProjected","cSince"].forEach(id=>$(id).textContent="—");$("qc").innerHTML="";$("lineSummary").textContent="No line list loaded. Manual onset dates can still be entered below.";$("reportText").textContent="Complete the outbreak profile and analyses, then generate the summary.";applyRule();renderExp();drawCurve()}
document.addEventListener("DOMContentLoaded",()=>{$("reviewDate").value=new Date().toISOString().slice(0,10);$("disease").addEventListener("change",applyRule);$("calcOverview").onclick=overview;$("drawCurve").onclick=()=>drawCurve();$("updateClosure").onclick=()=>updateClosure();$("addExposure").onclick=addExposure;$("demo").onclick=demo;$("reset").onclick=reset;$("generateReport").onclick=report;$("copyReport").onclick=async()=>{await navigator.clipboard.writeText($("reportText").textContent);$("copyReport").textContent="Copied";setTimeout(()=>$("copyReport").textContent="Copy summary",1200)};$("printReport").onclick=()=>window.print();["indexOnset","secondOnset","lastOnset"].forEach(id=>$(id).addEventListener("change",e=>{e.target.dataset.manual="1";updateClosure()}));["requiredDays","reviewDate"].forEach(id=>$(id).addEventListener("change",()=>updateClosure()));$("csvFile").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>analyze(parseCSV(r.result));r.readAsText(f)});applyRule();renderExp();drawCurve()});
